### ISSUE TITLE
[GET-search/] - search API results in 404

### ISSUE THREAD

**Issue by shangan23** [web-slate/google-search-clone-api#16]
![image](https://user-images.githubusercontent.com/3478542/157841762-e271c37c-e850-467c-a3de-28fd8d98fbf8.png)

**Comment by shangan23** [comment]
`https://google-search-app-api.herokuapp.com/api/search?searchterm=youtube`

URL which works.

**Comment by jpukg** [comment]
PR has been created. https://github.com/web-slate/google-search-clone-api/pull/21
