### ISSUE TITLE
[GET-search/] - translate and traductor keywords throws 500 error

### ISSUE THREAD

**Issue by shangan23** [web-slate/google-search-clone-api#17]
![image](https://user-images.githubusercontent.com/3478542/157842956-28e239bd-f6e0-48a7-8806-705cdb13e8f4.png)
![image](https://user-images.githubusercontent.com/3478542/157843188-d5a60791-e46f-44f5-992a-fd249da5ba74.png)

**Comment by jpukg** [comment]
PR has been created. https://github.com/web-slate/google-search-clone-api/pull/21
